name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --workspace --release --verbose
    - name: Build
      run: cargo build --workspace --release --verbose
    - name: Run tests (defaults)
      run: cargo test --workspace --release --verbose
    - name: Run tests (minimal)
      run: cargo test --workspace --release --verbose --no-default-features
